name: Publish release

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]
    paths-ignore: ["**.md"]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-info:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate.outputs.version }}
      changelog: ${{ steps.generate.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
      - name: Generate release info
        id: generate
        run: |
          ./release-info.sh # inputs: taken from env; outputs: version, changelog

  release-github:
    if: github.ref == 'refs/heads/main' && needs.release-info.outputs.changelog != ''
    runs-on: ubuntu-latest
    needs:
      - release-info
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release-info.outputs.version }}
          body: ${{ needs.release-info.outputs.changelog }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "## :rocket: Release ${{ needs.release-info.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "A new release is available over at https://github.com/${{ github.repository }}/releases/tag/${{ needs.release-info.outputs.version }}." >> $GITHUB_STEP_SUMMARY
